services:

  devcontainer:

    # To make the environment more explicit
    hostname: microlind-builder

    init: true

    # Keep the container alive
    command: "sleep infinity"

    network_mode: "host"

    build:
      context: .

    volumes:
      - type: bind
        source: ../
        target: /home/ubuntu/microlind

      #- type: bind
      #  source: ${HOME}/.gitconfig
      #  target: ${HOME}/.gitconfig

      #- type: bind
      #  source: ${HOME}/.ssh
      #  target: ${HOME}/.ssh
