services:

  devcontainer:

    # To make the environment more explicit
    hostname: microlind-builder

    init: true

    # Keep the container alive
    command: "sleep infinity"

    network_mode: "host"

    user: ${USER_NAME:-ubuntu}
    working_dir: /home/${USER_NAME:-ubuntu}

    build:
      context: .
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        USER_NAME: ${USER_NAME:-ubuntu}

    volumes:
      - type: bind
        source: ../
        target: /home/${USER_NAME:-ubuntu}/microlind

      #- type: bind
      #  source: ${HOME}/.gitconfig
      #  target: ${HOME}/.gitconfig

      #- type: bind
      #  source: ${HOME}/.ssh
      #  target: ${HOME}/.ssh
